config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  get "profile/:id", as: :profile ,to: "profiles#show"
  get "/bugs", to: "bugs#view"
  devise_for :users,controllers: {registrations: "registrations"}
  resources :projects do
    resources :project_users
    resources :bugs
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bug.rb
class Bug < ActiveRecord::Base

mount_uploader :image_path, ImageUploader

	belongs_to :projects
  belongs_to :creator ,class_name: "User", foreign_key: :created_by
    belongs_to :solver ,class_name: "User", foreign_key: :solved_by, optional: true
	validates :title, presence: true,
  			length: { minimum: 3, maximum: 25 }

  validates :description, presence: true,
  			length: { minimum: 3, maximum: 25 }

  validates :status, presence: true

  validates :type, presence: true

  validates :deadline, presence: true
  validates_processing_of :image_path
validate :image_size_validation
 
private
  def image_size_validation
    errors[:image_path] << "should be less than 5000KB" if image_path.size > 5.megabytes
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
	
  belongs_to :manager, class_name: "User", foreign_key: :manager_id 
	has_many :project_users, dependent: :destroy
	has_many :users , through: :project_users
	has_many :bugs, dependent: :destroy

  validates :title, presence: true,
        length: { minimum: 3, maximum: 25 }

  validates :description, presence: true,
        length: { minimum: 3, maximum: 25 }

end

app/models/project_user.rb
class ProjectUser < ActiveRecord::Base
	belongs_to :project
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :managed_projects, class_name: "Project" ,foreign_key: :manager_id
  has_many :project_users  
  has_many :projects, through: :project_users
  has_many :bugs, class_name: "Bug", foreign_key: :created_by
  has_many :bugs_solved, class_name: "Bug", foreign_key: :solved_by



  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true,
  			length: { minimum: 3, maximum: 25 }

  validates :user_type, presence: true

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, length: { maximum: 105 },
  			uniqueness: { case_sensitive: false },
  			format: { with: VALID_EMAIL_REGEX }


  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
	include Pundit
	protect_from_forgery with: :exception

	 rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_user!
  before_action :set_project, except:[:view]
  before_action :set_bug, only:[:edit,:destroy,:update]

  def index
    @bugs = Bug.where(project_id: @project.id)
  end

  def view
    @bugs = Bug.all
    render 'index'
  end

  def new 
    @bug = Bug.new
  end

  def edit

  end

  def create 
    @bug = current_user.bugs.new(bug_params)
    @bug.project = @project
    if @bug.save
      flash[:success] = "Bug was successfuly created"
      redirect_to root_path
    else
      render 'new'
    end 
  end

  def update
    if current_user.user_type == "Developer"
      @bug.solver = current_user
    elsif current_user.user_type == "QA"
      @bug.creator = current_user
    end  
      @bug.project = @project
      update_bug
  end

  def destroy
    if  @bug.destroy        
      flash[:success] = "Bug was successfuly deleted"
      redirect_to project_bugs_path(@project.id)
    end
  end

  def update_bug
    if @bug.update(bug_params)
      flash[:success] = "Bug was successfuly updated"
      redirect_to root_path
    else
      render 'edit'
    end 
  end

  private
  def bug_params
    params.require(:bug).permit(:title, :description,:status,:type,:deadline,:image_path,:remove_image_path,@project_id)
  end

  def authorize_user!
    authorize current_user,  policy_class: BugPolicy
  end

  def set_project
    if Project.exists?(params[:project_id])
      @project = Project.find(params[:project_id])
    else
      flash[:danger] = "project does not exists"
      redirect_to projects_path()
    end
  end

  def set_bug
    if Bug.exists?(params[:id])
      @bug= Bug.find(params[:id])
    else
      flash[:danger] = "Bug does not exists"
      redirect_to projects_path()
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
		
	end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	
	def show
		if signed_in?
		  @user = User.find(current_user.id)
    else
			redirect_to new_user_session_path
		end
	end
	
end

app/controllers/project_users_controller.rb
class ProjectUsersController < ApplicationController
  before_action :set_project

  def new
    @project_user = ProjectUser.new
    @users = User.where("user_type" => "Developer") 
  end

  def create
    @developer = User.find(params[:project_user][:user_id].to_i) 
    if !@developer.projects.include?(@project)
      @project_user = ProjectUser.new(developer_params)
      @project_user.project = @project
      @project_user.save
      flash[:success] = "Developer added successfully"
      redirect_to projects_path()
    else
      flash[:success] = "Developer Already exists"
      redirect_to projects_path()
    end
  end

  def developer_params
    params.require(:project_user).permit(:user_id)  
  end

  def set_project
    if Project.exists?(params[:project_id])
     @project = Project.find(params[:project_id])
    else
     flash[:danger] = "project does not exists"
     redirect_to projects_path()
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :authenticate_user!
  before_action :authorize_user!
  before_action :set_project, only: [:destroy, :edit, :update]
  def new
		@project = Project.new
	end

	def index
		@projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def create
    byebug
      @project = current_user.managed_projects.new(project_params)
    if @project.save
      flash[:success] = "project was successfuly created"
      redirect_to root_path
    else
      flash[:danger] = "project was not created"
      render 'new'
    end	
  end

  def update
    if @project.update(project_params)
      flash[:success] = "project was successfuly update"
      redirect_to root_path
    else
      flash[:danger] = "project was not created"
      render 'new'
    end 
  end

  def destroy
    if @project.destroy       
      flash[:success] = "project was successfuly deleted"
      redirect_to projects_path()
    end
  end 

  def edit

  end

  def set_project
    if Project.exists?(params[:id])
      @project = Project.find(params[:id])
    else
      flash[:danger] = "project does not exists"
          redirect_to projects_path()
    end
  end

  def authorize_user!
    authorize current_user 
  end

  def project_params
    params.require(:project).permit(:title, :description)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

private

def sign_up_params
params.require(:user).permit(:name,:user_type,:email,:password,:password_confirmation)
end

def account_update_params
params.require(:user).permit(:name,:user_type,:email,:password,:password_confirmation,:current_password)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bugs/_bug.html.erb
<% bugs.each do |bug| %>
 <div class="row" >
  <div class="col-xs-8 col-xs-offset-2">
    <div class="well well-lg" align="center">
      <% if  bug.image_path.url!=nil %>
       <%= image_tag bug.image_path.url ,size: 100%>
      <% end %>
    <div class="project-title">
     <%= bug.title %>
    </div>

    <div class="project-body">
     <%= truncate(bug.description, length: 100) %>
    </div>
    
    <div class="project-meta-data">
     <small>
         Created By: <%= bug.creator.name  %>,
         <%= time_ago_in_words(bug.created_at) %> ago, 
         last updated: <%= time_ago_in_words(bug.updated_at) %> ago
     
     </small>
    
      <% if bug.status != "New"%>
        <br>
          <small>
               <%=bug.status %> By: <%= bug.solver.name %>
          </small>
      <% end %>
    </div>

    <% if signed_in? && current_user.id == bug.created_by  %>
      <div class="project-actions">
        <%= link_to "Edit this Bug", edit_project_bug_path(bug.project_id,bug.id), class: "btn btn-xs btn-primary" %>
        <%= link_to "Delete this Bug", project_bug_path(bug.project_id,bug.id), method: :delete,
        data: { confirm: "Are you sure you want to delete the article?"},
        class: "btn btn-xs btn-danger" %>
        
        <%elsif signed_in? && current_user.user_type == "Developer"%>
          <%= link_to "Resolve this Bug", edit_project_bug_path(bug.project_id,bug.id), class: "btn btn-xs btn-primary" %>
            
       </div>
     <% end %>
   </div>
 </div>
</div>
<% end %>

app/views/bugs/_form.html.erb
<div class="col-md-4 col-xs-4 col-xs-offset-4 col-md-offset-4">
  <%= form_for(@bug,:url => project_bugs_path, :html => {class: "form-vertical", role: "form"} ) do |f| %>
  <%= render 'layouts/error', {obj: @bug} %>
    <div class="form-group">
      <div class="control-label">
        <%= f.label :title %>
      </div>
      <%= f.text_field :title, class: "form-control", placeholder: "Enter Title", autofocus: true, autocomplete: "title" %>   
    </div>

    <div class="form-group">
      <div class="control-label">
        <%= f.label :description %>
      </div>
        <%= f.text_field :description, class: "form-control", placeholder: "Enter description", autofocus: true, autocomplete: "description" %>
    </div>
    
    <div class="form-group">
      <div class="control-label">
        <%= f.label :type %>
      </div>
      <%= f.select :type, options_for_select([["Select One", ""], "Features", "Bug"]), { :include_blank => false },  {:class => 'form-control'} %>
    </div>

    <div class="form-group">
     <div class="control-label">
       <%= f.label :status %>
     </div>
     <%= f.select :status, options_for_select([["Select One", ""], "New", "Started", "Completed","Resolved"]), { :include_blank => false },  {:class => 'form-control'} %>
    </div>

    <div class="form-group">
      <div class="control-label">
        <%= f.label :deadline %>
      </div>
      <%= f.text_field :deadline, class: 'form-control',"data-provide" => "datepicker" ,"data-date-start-date"=>"-0d" %>
    </div>
    
    <div class="form-group">
      <%= f.submit(@bug.new_record? ? "Create" : "Update", class: 'btn btn-primary btn-lg') %>
    </div>
  <% end %>
</div>

app/views/bugs/edit.html.erb
<h1 align="center">
  <% if current_user.user_type == "Developer" %>
    Resolve Bug
  <% elsif current_user.user_type == "QA" %>
    Edit Bug
  <% end %>
</h1>

<div class="col-md-4 col-xs-4 col-xs-offset-4 col-md-offset-4">
  <%= form_for(@bug,:url => project_bug_path, :html => {class: "form-vertical", role: "form",multipart: true} ) do |f| %>
  <%= render 'layouts/error', {obj: @bug} %>
    <% if current_user.user_type == "QA" %>
     <div class="form-group">
      <div class="control-label">
        <%= f.label :title %>
      </div>
        <%= f.text_field :title, class: "form-control", placeholder: "Enter Title", autofocus: true, autocomplete: "title" %>   
    </div>

    <div class="form-group">
      <div class="control-label">
        <%= f.label :description %>
      </div>
        <%= f.text_field :description, class: "form-control", placeholder: "Enter description", autofocus: true, autocomplete: "description" %>
    </div>
    
    <div class="form-group">
       <div class="control-label">
        <%= f.label :type %>
    </div>
     
      <%= f.select :type ,options_for_select([["Select One", ""], "Features", "Bug"],@bug.type), { :include_blank => false },  {:class => 'form-control'} %>
    </div>

    <div class="form-group">
      <div class="control-label">
        <%= f.label :status %>
      </div>
     
      <%= f.select :status, options_for_select([["Select One", ""], "New", "Started", "Completed","Resolved"],@bug.status), { :include_blank => false },  {:class => 'form-control'} %>
     
    </div>

    <div class="form-group">
      <div class="control-label">
        <%= f.label :deadline %>
      </div>
     
      <%= f.text_field :deadline, class: 'form-control',"data-provide" => "datepicker" ,"data-date-start-date"=>"-0d" %>
     
    </div>

    <div class="form-group">
      <div class="control-label">
        <%= f.label :image_path %>
      </div>
        <%= f.file_field :image_path %>
        <% if f.object.image_path? %>
      <%= image_tag f.object.image_path.url ,size: 100%>
      <%= f.label :remove_image %>
      <%= f.check_box :remove_image_path %> 
    <% end %>
      </div> 
       <% elsif current_user.user_type == "Developer" %> 
       <div class="form-group">
      <div class="control-label">
        <%= f.label :status %>
      </div>
     
      <%= f.select :status, options_for_select([["Select One", ""], "New", "Started", "Completed","Resolved"],@bug.status), { :include_blank => false },  {:class => 'form-control'} %>
     
    </div>
    <% end %>

    <div class="form-group">
      <%= f.submit(@bug.new_record? ? "Create" : "Update", class: 'btn btn-primary btn-lg') %>
    </div>
  <% end %>
</div>

app/views/bugs/index.html.erb
<% if @bugs.count>0%>
	<div align="center">
		<h1> List of Bugs</h1>
	</div>
<%= render "bugs/bug", bugs: @bugs%>
<% else %>
<div align="center">
  <h1> No Bug Found</h1>
</div>
<% end %>

app/views/bugs/new.html.erb
<h1 align="center">
	Add New Bug
</h1>

<div class="col-md-4 col-xs-4 col-xs-offset-4 col-md-offset-4">
  <%= form_for(@bug,:url => project_bugs_path,:html => {multipart: true,class: "form-vertical", role: "form"} ) do |f| %>
<%= render 'layouts/error', {obj: @bug} %>
     <div class="form-group">
      <div class="control-label">
        <%= f.label :title %>
      </div>
        <%= f.text_field :title, class: "form-control", placeholder: "Enter Title", autofocus: true, autocomplete: "title" %>   
    </div>

    <div class="form-group">
      <div class="control-label">
        <%= f.label :description %>
      </div>
        <%= f.text_field :description, class: "form-control", placeholder: "Enter description", autofocus: true, autocomplete: "description" %>
    </div>
    
      <div class="form-group">
      <div class="control-label">
        <%= f.label :type %>
      </div>
     
      <%= f.select :type, options_for_select([["Select One", ""], "Features", "Bug"],@bug.type), { :include_blank => false },  {:class => 'form-control'} %>
     
    </div>

       <div class="form-group">
      <div class="control-label">
        <%= f.label :status %>
      </div>
     
      <%= f.select :status, options_for_select([["Select One", ""], "New", "Started", "Completed","Resolved"],@bug.status), { :include_blank => false },  {:class => 'form-control'} %>
     
    </div>

      <div class="form-group">
      <div class="control-label">
        <%= f.label :deadline %>
      </div>
     
      <%= f.text_field :deadline, class: 'form-control',"data-provide" => "datepicker" ,"data-date-start-date"=>"+0d" %>
     
    </div>

    <div class="form-group">
      <div class="control-label">
        <%= f.label :image_path %>
      </div>
        <%= f.file_field :image_path %>
      </div>  
    
    

    <div class="form-group">
      <%= f.submit(@bug.new_record? ? "Create" : "Update", class: 'btn btn-primary btn-lg') %>
    </div>
  <% end %>
</div>

app/views/layouts/_error.html.erb
<% if obj.errors.any? %>

<h2>The following errors prevented the object from getting created</h2>
<ul>

<% obj.errors.full_messages.each do |msg| %>

<li><%= msg %></li>

<% end %>

</ul>
<% end %>

app/views/layouts/_messages.html.erb
<div class="container">
  <div class=" row col-md-10 col-md-offset-1">
      <% flash.each do |type, msg| %>
        <% if type == "notice" %>
          <div class="alert alert-success">
        <% elsif type == "alert" %>
          <div class="alert alert-danger">
        <% else %>
          <div class='alert alert-<%= "#{type}" %>'>
        <% end %>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <ul>
          <li>
            <%= msg %>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to "Test", root_path, class:"navbar-brand" %> 
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %> </li>
        <li><%= link_to "Bugs", bugs_path %> </li>
       
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Projects <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'New Project', new_project_path%></li>
             <li><%= link_to 'View Projects', projects_path%></li>
          </ul>
        </li>
      </ul>
    
      <ul class="nav navbar-nav navbar-right">
        <% if signed_in? %>
          <li><%= link_to 'Log out' ,destroy_user_session_path, method: :delete %></li>
        <% else %><li>
        <%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to 'Log in' ,new_user_session_path%></li>
        <% end %>
        <% if signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile  <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "View", profile_path(current_user) %></li>    
          </ul>
        </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation'%>
    <%= render 'layouts/messages'%>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
	<div class="row">
		<div align="center">
			<h1>Welcome To Testing App</h1>
				<div align="center">
					<br>
					<% if !signed_in? %>
						<h3> New User Need To Sign Up</h3>
						<%= link_to '<button class="btn-lg btn-primary" type="button">Sign Up</button>'.html_safe, new_user_registration_path %>
					<% else %>
						<h3> Logged in as: <%= current_user.user_type%></h3>
					<% end %>
				</div>
		</div>
	</div>
</div>

app/views/profiles/show.html.erb
<h1 align="center"> 
	Welcome to <%= @user.name %> page
</h1>


<div class="row">
	<div class="col-md-8 col-md-offset-2 center">
    <% if @user.user_type == "Manager" %>
				<%= render 'projects/project', obj: @user.managed_projects %>
    <% elsif @user.user_type == "Developer" %>      
        <%= render 'projects/project', obj: @user.projects %>
     <% else %>
        <%= render 'bugs/bug', bugs: @user.bugs %>
     <% end %>   
			
		
	</div>
</div>

app/views/project_users/new.html.erb
<div align="center">
	<h1> <%= @project.title %> </h1>
</div>

<div class="col-md-4 col-xs-4 col-xs-offset-4 col-md-offset-4">
  <%= form_for(@project_user,:url => project_project_users_path, :html => {class: "form-vertical", role: "form"} ) do |f| %>

	
	<div class="form-group">
      <div class="control-label">
        <%= f.label "Developer List" %>
      </div>
     
      <%= f.select :user_id, options_for_select(@users.collect { |player| ["#{player.name}", player.id] }), { :include_blank => false },  {:class => 'form-control'} %>
     
    </div>

	<%= f.submit("Add", class: 'btn btn-primary btn-lg') %>
	<%end %>



</div>

app/views/projects/_form.html.erb
<div class="col-md-4 col-xs-4 col-xs-offset-4 col-md-offset-4">
  <%= form_for(@project, :html => {class: "form-vertical", role: "form"} ) do |f| %>
    
     <div class="form-group">
      <div class="control-label">
        <%= f.label :title %>
      </div>
        <%= f.text_field :title, class: "form-control", placeholder: "Enter Title", autofocus: true, autocomplete: "title" %>   
    </div>

    <div class="form-group">
      <div class="control-label">
        <%= f.label :description %>
      </div>
        <%= f.text_field :description, class: "form-control", placeholder: "Enter description", autofocus: true, autocomplete: "description" %>
    </div>
  
    <div class="form-group">
      <%= f.submit(@project.new_record? ? "Create" : "Update", class: 'btn btn-primary btn-lg') %>
    </div>
  <% end %>
</div>

app/views/projects/_project.html.erb
<% obj.each do |project| %>

<div class="row">

<div class="col-xs-8 col-xs-offset-2">

<div class="well well-lg">

<div class="project-title">

<%= link_to project.title, project_path(project) %>

</div>
<div class="project-body">

<%= truncate(project.description, length: 100) %>
	
<div class="project-meta-data">
<small>
	Created By: <%=project.manager.name  %>,
	<%= time_ago_in_words(project.created_at) %>
	last updated: <%= time_ago_in_words(project.updated_at) %> ago
	

</small>
</div>
</div>
<% if signed_in? && current_user.user_type == "Manager" %>
<div class="project-actions">

<%= link_to "Add developer",  new_project_project_user_path(project.id), class: "btn btn-xs btn-success" %>
<%= link_to "Edit this project", edit_project_path(project), class: "btn btn-xs btn-primary" %>

<%= link_to "Delete this project", project_path(project), method: :delete,

data: { confirm: "Are you sure you want to delete the article?"},

class: "btn btn-xs btn-danger" %>
<% elsif  signed_in? && current_user.user_type =="QA" %>
<%= link_to "Add Bug", new_project_bug_path(project), class: "btn btn-xs btn-warning" %>


</div>
<% end %>
</div>

</div>

</div>

<% end %>

app/views/projects/edit.html.erb
<div align="center">
  <h2>Edit Project</h2>
</div>
<%= render "projects/form"%>

app/views/projects/index.html.erb
<div align="center">
	<h1> List of projects</h1>
</div>
<%= render "projects/project", obj: @projects %>

app/views/projects/new.html.erb
<div align="center">
  <h2>Creat New Project</h2>
</div>
<%= render "projects/form"%>

app/views/projects/show.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="well well-lg">
      <div class="project-title">
        <%= link_to @project.title, project_path(@project) %>
          
      </div>

      <div class="project-body">

        <%= truncate(@project.description, length: 100) %>
        <br>
        <br>
     
        <b> List of Developers</b>
    
        <ul>
	         <% @project.users.each do |user| %>
            <% if user.user_type =="Developer"%>
              <li> <%=user.name%></li>
            <% end%>
          <%end%>
        </ul>
    
      <%if @project.bugs.count>0 %>
       <%= link_to 'View Bugs', project_bugs_path(@project.id),class: "btn btn-xs btn-primary"%>
       <%end %>
        <div class="project-meta-data">
          <small>
        	 <% @project.users.each do |user| %>
        	   <% if user.user_type =="Manager"%>
        	     Created By: <%=user.name  %>,
        	     <%= time_ago_in_words(@project.created_at) %>
        	     last updated: <%= time_ago_in_words(@project.updated_at) %> ago
        	   <% end %>
            <% end %>
          </small>
        </div>
      </div>
        	
           <div class="project-actions">
            <% if signed_in? && current_user.user_type == "Manager" %>
              <%= link_to "Add developer",  new_project_project_user_path(@project.id), class: "btn btn-xs btn-success" %>
              <%= link_to "Edit this project", edit_project_path(@project), class: "btn btn-xs btn-primary" %>
              <%= link_to "Delete this project", project_path(@project), method: :delete,
                data: { confirm: "Are you sure you want to delete the article?"},
                class: "btn btn-xs btn-danger" %>
            <% elsif signed_in? &&  current_user.user_type == "QA"  %>
              <%= link_to "Add Bug", new_project_bug_path(@project), class: "btn btn-xs btn-warning" %>
            <% end %>
          </div>
       
     </div>
    </div>
  </div>